# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-02-21 13:47
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20170221_1346'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailberifyrecord',
            name='send_time',
            field=models.DateTimeField(default=datetime.datetime.now, verbose_name='创建时间'),
        ),
        migrations.AlterField(
            model_name='emailberifyrecord',
            name='send_type',
            field=models.CharField(choices=[('register', '注册'), ('forget', '找回密码')], max_length=5, verbose_name='类型'),
        ),
    ]
